name = "Cours_ED"
version = "0.1.0"
defaultTargets = ["CoursED"]

[[lean_lib]]
name = "CoursED"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "lean4.15.0-rc1"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.15.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"
